"""初始化

Revision ID: 70afdead0cd3
Revises: 
Create Date: 2018-05-27 09:49:18.611272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70afdead0cd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_category',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('modTime', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('modTime', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portrait', sa.String(length=50), nullable=True),
    sa.Column('nick_name', sa.String(length=20), nullable=True),
    sa.Column('signature', sa.String(length=200), nullable=True),
    sa.Column('public_count', sa.Integer(), nullable=True),
    sa.Column('fans_count', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_info',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('modTime', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_title', sa.String(length=32), nullable=True),
    sa.Column('news_type', sa.Integer(), nullable=True),
    sa.Column('news_summary', sa.String(length=256), nullable=True),
    sa.Column('news_content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('varify_status', sa.SmallInteger(), nullable=True),
    sa.Column('refuse_reason', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['news_type'], ['news_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user_follow',
    sa.Column('follow_user_id', sa.Integer(), nullable=False),
    sa.Column('follow_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follow_by_user_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['follow_user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('follow_user_id', 'follow_by_user_id')
    )
    op.create_table('tb_user_news',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'news_id')
    )
    op.create_table('user_comment',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('modTime', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_content', sa.String(length=256), nullable=True),
    sa.Column('nice_count', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['user_comment.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_comment')
    op.drop_table('tb_user_news')
    op.drop_table('tb_user_follow')
    op.drop_table('news_info')
    op.drop_table('user_info')
    op.drop_table('news_category')
    # ### end Alembic commands ###
