"""修改signature

Revision ID: 8a16f035e6a7
Revises: 
Create Date: 2018-05-30 09:39:54.012477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a16f035e6a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user_follow', sa.Column('origin_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('tb_user_follow_ibfk_1', 'tb_user_follow', type_='foreignkey')
    op.create_foreign_key(None, 'tb_user_follow', 'user_info', ['origin_user_id'], ['id'])
    op.drop_column('tb_user_follow', 'follow_by_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user_follow', sa.Column('follow_by_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tb_user_follow', type_='foreignkey')
    op.create_foreign_key('tb_user_follow_ibfk_1', 'tb_user_follow', 'user_info', ['follow_by_user_id'], ['id'])
    op.drop_column('tb_user_follow', 'origin_user_id')
    # ### end Alembic commands ###
