"""添加news_pic

Revision ID: ebafa7d97330
Revises: 07e3c826befe
Create Date: 2018-05-31 13:45:14.871139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebafa7d97330'
down_revision = '07e3c826befe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_info', sa.Column('news_pic', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_info', 'news_pic')
    # ### end Alembic commands ###
